-- AlterTable
ALTER TABLE "Job" ADD COLUMN "category" TEXT;
ALTER TABLE "Job" ADD COLUMN "city" TEXT;
ALTER TABLE "Job" ADD COLUMN "contractType" TEXT;
ALTER TABLE "Job" ADD COLUMN "country" TEXT;
ALTER TABLE "Job" ADD COLUMN "expiresAt" DATETIME;
ALTER TABLE "Job" ADD COLUMN "publishedAt" DATETIME;
ALTER TABLE "Job" ADD COLUMN "qualifications" TEXT;
ALTER TABLE "Job" ADD COLUMN "region" TEXT;
ALTER TABLE "Job" ADD COLUMN "salaryCurrency" TEXT;
ALTER TABLE "Job" ADD COLUMN "salaryPeriod" TEXT;
ALTER TABLE "Job" ADD COLUMN "state" TEXT;
ALTER TABLE "Job" ADD COLUMN "workingHours" TEXT;
